# Generated by Django 4.2.3 on 2023-07-05 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Web-dev', 'Web-dev'), ('Machine Learning', 'Machine Learning')], default='Web-dev', max_length=160, null=True)),
            ],
        ),
    ]
