# Generated by Django 4.2.3 on 2023-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('d', 'Drafted'), ('p', 'Published')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
