# Generated by Django 4.1.4 on 2023-07-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_document_alter_postmodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
